version: '3.8'

services:
  baileys:
    build: .
    container_name: whatsapp-baileys
    volumes:
      - ../baileys_data:/usr/src/app/baileys-auth-directory
    working_dir: /usr/src/app
    environment:
      - AUTH_FILE_PATH=/usr/src/app/baileys-auth-directory/baileys-auth.json
    restart: unless-stopped
